name: Docker CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image
      run: cd 20.04/ && docker build -t boreddevco/gigalixir-ubuntu:20.04 .

    - name: Publish image
      run: cd 20.04/ && docker push boreddevco/gigalixir-ubuntu:20.04
